name = "jelilakjaly/tet"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'jelilakjaly/tet'"

[repository]
user = "jelilakjaly"
project = "tet"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"
